interface IPlanosDeConta {
  codigo: string;
  nomeDaConta: string;
  tipo: string;
  aceitaLancamentos: boolean;
}

export const planosDeConta: IPlanosDeConta[] = [
  {
    codigo: '1',
    nomeDaConta: 'Receitas',
    tipo: 'Receita',
    aceitaLancamentos: false,
  },
  {
    codigo: '1.1',
    nomeDaConta: 'Taxa condominial',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.2',
    nomeDaConta: 'Reserva de dependência',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.3',
    nomeDaConta: 'Multas',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.4',
    nomeDaConta: 'Juros',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.5',
    nomeDaConta: 'Multa condominial',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.6',
    nomeDaConta: 'Água',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.7',
    nomeDaConta: 'Gás',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.8',
    nomeDaConta: 'Luz e energia',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.9',
    nomeDaConta: 'Fundo de reserva',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.10',
    nomeDaConta: 'Fundo de obras',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.11',
    nomeDaConta: 'Rendimento de poupança',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.12',
    nomeDaConta: 'Rendimento de investimentos',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.13',
    nomeDaConta: 'Correção monetária',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.14',
    nomeDaConta: 'Transferência entre contas',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.15',
    nomeDaConta: 'Pagamento duplicado',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.16',
    nomeDaConta: 'Cobrança',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.17',
    nomeDaConta: 'Crédito',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.18',
    nomeDaConta: 'Água mineral',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.19',
    nomeDaConta: 'Estorno taxa de resgate',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.2',
    nomeDaConta: 'Acordo',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '1.21',
    nomeDaConta: 'Honorários',
    tipo: 'Receita',
    aceitaLancamentos: true,
  },
  {
    codigo: '2',
    nomeDaConta: 'Despesas',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.1',
    nomeDaConta: 'Com pessoal',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.1.1',
    nomeDaConta: 'Salário',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.2',
    nomeDaConta: 'Adiantamento salarial',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.3',
    nomeDaConta: 'Hora extra',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.4',
    nomeDaConta: 'Férias',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.5',
    nomeDaConta: '13º salário',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.6',
    nomeDaConta: 'Adiantamento 13º salário',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.7',
    nomeDaConta: 'Adicional de função',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.8',
    nomeDaConta: 'Aviso prévio',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.9',
    nomeDaConta: 'INSS',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.10',
    nomeDaConta: 'FGTS',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.11',
    nomeDaConta: 'PIS',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.12',
    nomeDaConta: 'Vale refeição',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.13',
    nomeDaConta: 'Vale transporte',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.14',
    nomeDaConta: 'Cesta básica',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.1.15',
    nomeDaConta: 'Acordo trabalhista',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2',
    nomeDaConta: 'Mensais',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.2.1',
    nomeDaConta: 'Energia elétrica',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.2',
    nomeDaConta: 'Água e esgoto',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.3',
    nomeDaConta: 'Taxa de administração',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.4',
    nomeDaConta: 'Gás',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.5',
    nomeDaConta: 'Seguro obrigatório',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.6',
    nomeDaConta: 'Telefone',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.2.7',
    nomeDaConta: 'Softwares e aplicativos',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.3',
    nomeDaConta: 'Financeiro',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.3.1',
    nomeDaConta: 'Registro de boletos',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.3.2',
    nomeDaConta: 'Processamento de boletos',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.3.3',
    nomeDaConta: 'Registro e processamento de boletos',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.3.4',
    nomeDaConta: 'Resgates',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.4',
    nomeDaConta: 'Manutenção',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.4.1',
    nomeDaConta: 'Elevador',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.4.2',
    nomeDaConta: 'Limpeza e conservação',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.4.3',
    nomeDaConta: 'Jardinagem',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5',
    nomeDaConta: 'Diversas',
    tipo: 'Despesa',
    aceitaLancamentos: false,
  },
  {
    codigo: '2.5.1',
    nomeDaConta: 'Honorários de advogado',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.2',
    nomeDaConta: 'Xerox',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.3',
    nomeDaConta: 'Correios',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.4',
    nomeDaConta: 'Despesas judiciais',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.5',
    nomeDaConta: 'Multas',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.6',
    nomeDaConta: 'Juros',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
  {
    codigo: '2.5.7',
    nomeDaConta: 'Transferência entre contas',
    tipo: 'Despesa',
    aceitaLancamentos: true,
  },
];
